### ISSUE TITLE
HTTP Header Tool

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#16]
MVP: 
- Text box for user to enter domain name or IP
- Button for sending the request
- Text area to show the HTTP header that was sent back from the requested destination

**Comment by tyoung-99** [comment]
1st iteration
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/d47f5d63-6092-4a7e-9ba6-929fcc2e75fc)
Works w/ URLs, still needs IP support.
Working on prettying output

**Comment by tyoung-99** [comment]
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/7e9c067b-b44b-4418-99fe-8a68046042a4)
Now works w/ URLs/IPs. Handles errors in each.
