### ISSUE TITLE
Subnet Scanner

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#19]
Could be added to the current subnet calculator as either another option, or as a default.

- Resolve the geographical locations of the IP addresses and display on a map
- Use a library (matplotlib or plotly) for visualization
- Handle edge cases and errors like unreachable hosts or timeouts

**Comment by tyoung-99** [comment]
First iteration
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/4cd40395-c154-4c4c-a952-fe89accc682b)
Slow b/c of limit to API calls per minute, need to find better method of getting IP location.
Also does nothing yet for unreachable hosts/timeouts.

**Comment by tyoung-99** [comment]
Second iteration
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/fb547ae3-ee5a-4ab2-bead-8b526f640c0b)
Using a free account on https://ipinfo.io/ to get 50K requests/month. It has different location information for IPs than the old one though, and I don't know which is accurate.
