### ISSUE TITLE
NS Lookup

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#22]
MVP:

- Text box for user to input a domain name
- button to send request
- text area to show DNS records that were found

**Comment by oavf15** [comment]
The first early iteration uses the socket library from Python.



<img width="1512" alt="NS Lookup 1" src="https://github.com/TheSirLancelot/Netulla/assets/48740780/d3752549-e22c-45be-8bb2-bc7eedafb6e9">

More testing still needs to be done.

**Comment by TheSirLancelot** [comment]
> Could also look at using https://pypi.org/project/dnspython/

Oooh yea this package looks Like it's exactly what we need. I failed to look at the data type the record is returned in, but assuming we can pretty it up for displaying nicely on the webpage that'll be perfect.

**Comment by oavf15** [comment]
Changed function to use resolve from https://pypi.org/project/dnspython/ as well as update requirements.txt to install the dnspython toolkit version 2.4.2.



![Image](https://github.com/TheSirLancelot/Netulla/assets/48740780/0ed78099-6e5c-42e0-840d-a69190d9a506)

**Comment by oavf15** [comment]
Adjusted results to display better.


![Image](https://github.com/TheSirLancelot/Netulla/assets/48740780/fa83c8ee-e498-41c0-8338-ce05d3868bbd)

**Comment by oavf15** [comment]
Added unit test for ns_lookup function. Runs fine on my end.
<img width="779" alt="Screenshot 2023-11-22 at 12 41 57 PM" src="https://github.com/TheSirLancelot/Netulla/assets/48740780/753b2425-99a4-4a3a-a986-29452a3fc373">

**Comment by oavf15** [comment]
Adjusted test to fit new navigation bar style.
