### ISSUE TITLE
whatismyIP tool

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#25]
MVP:

- Button to send request
- Text area to show user's IP address
- map to show reported location based on lookup (don't use browser location, that's cheating)

**Comment by TheSirLancelot** [comment]
This functionality is already fulfilled by the IP Geolocation tool. Recommend coming up with a feature to implement instead of this.

**Comment by tyoung-99** [comment]
Will thought the IP geolocator started with the current IP, but it just starts with 8.8.8.8. Reopening.

Combining the tools and having it start with the current IP is a possible implementation.
