### ISSUE TITLE
Make the splash page pretty

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#43]
The main page of the web-app is still the "Shadow Suite" that we started with. We need to come up with something that matches what our app actually is.

**Comment by TheSirLancelot** [comment]
If there's anyone that can work on this sooner rather than later, it would be nice to have this updated prior to our presentation to the class (which I think is going to be scheduled for Thursday 9NOV23, if the prof sends it out).

**Comment by TheSirLancelot** [comment]
> If there's anyone that can work on this sooner rather than later, it would be nice to have this updated prior to our presentation to the class (which I think is going to be scheduled for Thursday 9NOV23, if the prof sends it out).

NOTE: You'll have to update the first test in frontend.py with the new title that you add. Assumedly will be 'Netulla' instead of 'Shadow Suite'..

**Comment by tyoung-99** [comment]
Updated to be particular to our app.
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/3260de85-19df-4134-a8e6-8bc4f51c0d18)
If anyone has more they want to add, or an idea of how to make the page itself look nice, feel free to add it.

**Comment by oavf15** [comment]
I changed around the navigation bar to make it a bit more aesthetic.


![Image](https://github.com/TheSirLancelot/Netulla/assets/48740780/91b34256-11d6-4c34-8e7a-af8210dbe36a)

Only problem is that some functions use the side bar for information input and if we move forward with the new navbar we would have to make some changes. Example of function using sidebar:



![Image](https://github.com/TheSirLancelot/Netulla/assets/48740780/86b572a7-9bb9-447f-9d46-205009e70de8)

**Comment by tyoung-99** [comment]
The only tools that use the sidebar for input so far are the template ones that we should remove before we submit the project, so as long as everyone keeps input on the pages going forward, not the sidebar, we should be fine.

**Comment by oavf15** [comment]
Closing this one as it is a duplicate.
