### ISSUE TITLE
Traceroute visualizer

### ISSUE THREAD

**Issue by nevermore23274** [TheSirLancelot/Netulla#5]
Adding a traceroute visualizer would add to the nuance of the project, as well would be neat to add in some sort of tables or visualization functions for hops.

**Comment by nevermore23274** [comment]
First iteration:



![Image](https://github.com/TheSirLancelot/CMSC495/assets/18754037/3a00cd02-f37d-4b9f-bbbd-1b31538f375b)

**Comment by nevermore23274** [comment]
Table and latency graph now work.

![vrett](https://github.com/TheSirLancelot/CMSC495/assets/18754037/80d2f4a9-7dda-4a52-ad26-353b8138aa4d)

**Comment by nevermore23274** [comment]
Changed the graph to be more precise, changed caching based on https://docs.streamlit.io/library/advanced-features/caching#migrating-from-stcache Still need to make changes to add a geolocation map, could also use more graphs on relevant information to be discussed and determined.

![meep](https://github.com/TheSirLancelot/CMSC495/assets/18754037/498a3bad-5189-4e05-80b9-4579103586e6)

**Comment by nevermore23274** [comment]
Removed tables and chart, placed in map with default inputs:
![catdog](https://github.com/TheSirLancelot/Netulla/assets/18754037/ca9bf7ec-4106-47be-bd1c-3ed3c9c5b6bf)

The inputs are formatted as such:
The packet paths (archs) format:
`[
    {
      "inbound": 72633,
      "outbound": 74735,
      "lon": -122.269029,
      "lat": 37.80787,
      "lon2": -122.271604,
      "lat2": 37.803664
    },`

And the server stops (circles) format:
`[
    {"name":"Lafayette (LAFY)","code":"LF","address":"3601 Deer Hill Road, Lafayette CA 94549","entries":"3481","exits":"3616","lon":-122.123801,"lat":37.893394},`

For now, I've saved these files locally. Hopefully I can get them to simply be read as strings each time the command is ran.

**Comment by nevermore23274** [comment]
Final:

![test_final](https://github.com/TheSirLancelot/Netulla/assets/18754037/aa025e0b-fa76-48b6-9060-26d798c11603)

Used these two links for data format in order for Streamlit to read the output correctly (regex formatted it for this):

https://raw.githubusercontent.com/streamlit/example-data/master/hello/v1/bart_path_stats.json
https://raw.githubusercontent.com/streamlit/example-data/master/hello/v1/bart_stop_stats.json

**Comment by TheSirLancelot** [comment]
So, I'm having some weird issues. I think part of it was that I was testing certain functionality after this was merged into dev that I should have tested prior to and I forgot (so that's on me). I reopened your branch, and I'm testing that specifically. Running into _some_ of the issues but not all, so I'm reopening this issue so we can figure them out before remerging with dev.

**Comment by TheSirLancelot** [comment]
It appears that my issues with the hops have been resolved using _only_ your branch:



![Image](https://github.com/TheSirLancelot/Netulla/assets/22830818/5df778ec-0a3e-47f7-a4fb-504681f05342)



I can test more tomorrow on a new PR with this and dev. I am still noticing that hitting 'enter' is not having the desired results though.
