### ISSUE TITLE
Bug in Subnet Calculator

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#59]
There's a bug currently that only properly calculates the network information if you use a .0 IP:

.1 or any other last octet:
![Image](https://github.com/TheSirLancelot/Netulla/assets/22830818/0294d519-fccd-4160-b088-6fe3477bd0c5)
![Image](https://github.com/TheSirLancelot/Netulla/assets/22830818/3e60963f-673d-49e2-a36d-c7ca4a75882f)

.0:
![Image](https://github.com/TheSirLancelot/Netulla/assets/22830818/172b000a-a70b-45fe-b1f3-32c426761681)

**Comment by tyoung-99** [comment]
Are we keeping the subnet calculator in? I thought that was one of the template tools that was going to be removed, same with the IP geolocation and network analysis tools.

**Comment by tyoung-99** [comment]
Removed strict mode from the network object, which requires host portion of IP to be 0.
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/c9805a4d-c0c5-410a-9e7b-a0ef40eaa287)
