### ISSUE TITLE
Come up with new features

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#80]
There were two planned features that are already implemented via other tools. Come up with 2 new features to replace them. 

Additionally, update the following with the new tools:
- Project Summary
- Test Plan
- User Guide
- Project Design (maybe? is it a living document?)
- Phase 3 milestone

**Comment by tyoung-99** [comment]
- Updated Project Summary, Test Plan, and Current Project Status to reflect change (#78).
- Updated User Guide template to reflect change (#79).
- The final submission includes "Design and Alternate designs," but unlike the other documents, Project Design isn't mentioned by name, so I don't know if that's expected to be included. I left the Project Design document alone for now, but it can be updated later if necessary.
- Added Regex tester (#81) to Phase 3 milestone.
